//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeCategory
    {
        public ChallengeCategory()
        {
            this.Challenges = new HashSet<Challenge>();
        }
    
        public decimal ChallengeCategoryId { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Challenge> Challenges { get; set; }
    }
}
