//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeRanking
    {
        public decimal ChallengeRankingId { get; set; }
        public decimal ChallegneId { get; set; }
        public double Ranking { get; set; }
        public decimal RankingGivenByUserId { get; set; }
        public System.DateTime RankingDate { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual User User { get; set; }
    }
}
