//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        public Challenge()
        {
            this.ChallengeRankings = new HashSet<ChallengeRanking>();
            this.UserChallenges = new HashSet<UserChallenge>();
            this.UserChallengeRankings = new HashSet<UserChallengeRanking>();
            this.UserChallengeRankings1 = new HashSet<UserChallengeRanking>();
        }
    
        public decimal ChallengeId { get; set; }
        public string Title { get; set; }
        public string Severity { get; set; }
        public int PersonsRequired { get; set; }
        public string Steps { get; set; }
        public string Precautions { get; set; }
        public string Note { get; set; }
        public int TimeLimit { get; set; }
        public decimal ChallengeCategoryId { get; set; }
        public string SupportingDocumentType { get; set; }
        public string SupportingDocumentPath { get; set; }
        public string ChallengeImagePath { get; set; }
        public decimal CreatedBy { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime CreatedDated { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ChallengeCategory ChallengeCategory { get; set; }
        public virtual UserChallenge UserChallenge { get; set; }
        public virtual ICollection<ChallengeRanking> ChallengeRankings { get; set; }
        public virtual ICollection<UserChallenge> UserChallenges { get; set; }
        public virtual ICollection<UserChallengeRanking> UserChallengeRankings { get; set; }
        public virtual ICollection<UserChallengeRanking> UserChallengeRankings1 { get; set; }
    }
}
