//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChallenge
    {
        public UserChallenge()
        {
            this.Challenges = new HashSet<Challenge>();
        }
    
        public decimal UserChallengeId { get; set; }
        public decimal UserId { get; set; }
        public decimal ChallengeId { get; set; }
        public System.DateTime ChallengeTakenDate { get; set; }
        public string ChallengeStatus { get; set; }
        public string Comments { get; set; }
        public string SupportingDocumentPath { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ICollection<Challenge> Challenges { get; set; }
        public virtual Challenge Challenge { get; set; }
        public virtual UserChallengeRanking UserChallengeRanking { get; set; }
        public virtual User User { get; set; }
    }
}
